version: '3.8'

services:
#  db:
#    image: mysql:8.0
#    container_name: mysql_container
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: admin
#      MYSQL_DATABASE: cms
#    ports:
#      - "3307:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      #DATABASE_URL: mysql+pymysql://root:root@host.docker.internal:3308/cms
      #DATABASE_URL: mysql+pymysql://root:admin@db/cms
      DATABASE_URL: mysql+pymysql://root:Vision-2025@74.48.111.163:3306/cms
      SECRET_KEY: your_secret_key_here
    volumes:
      - .:/cms_1  # Mounts current code to the container
  
#volumes:
#  mysql_data: {}

