version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Vision-2025
      MYSQL_DATABASE: cms
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: fastapi_app
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql+pymysql://root:Vision-2025@74.48.111.163/cms
      SECRET_KEY: your_secret_key_here
    volumes:
      - .:/cms_1  # Mounts your current code to the container

volumes:
  mysql_data: {}
